<a href="https://colab.research.google.com/github/Samiya-AW/NumPy-Numerical-Python-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

In [22]:
l = [1, 2, 3, 4]

In [23]:
# Convert list into an array

arr = np.array(l)
arr

type(arr)

numpy.ndarray

In [24]:
# Convert list into an array using np.asarray() and np.asanyarray() functions
l1 = [1, 2, 3, 4, 5]
arr1 = np.asarray(l1)
print(arr1)

l2 = [4, 5, 6, 100]
arr2 = np.asanyarray(l2)
arr2

[1 2 3 4 5]


array([  4,   5,   6, 100])

In [25]:
# Convert a list into a 2d array / matrix using np.matrix() function

mat = np.matrix(l2)
mat

# matrix is by default a 2d array
# matrix is a subset of an array

matrix([[  4,   5,   6, 100]])

In [26]:
# dimensions of array
# 2D array

array = np.array([[1, 2], [3, 4]])
print(array)
array

[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

In [27]:
# Print the total number of rows and columns in an array

array.shape

(2, 2)

In [28]:
# Size of an array / total number of elements in an array

array.size

4

In [29]:
# Dimension of an array

array.ndim

2

In [30]:
# 3D array

arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
    ])

print(arr_3d)
print("\nDimensions of arr_3d = ", arr_3d.ndim)
print("Shape (no. of rows and columns) of arr_3d = ", arr_3d.shape)
print("Total number of elements in arr_3d = ", arr_3d.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimensions of arr_3d =  3
Shape (no. of rows and columns) of arr_3d =  (2, 2, 3)
Total number of elements in arr_3d =  12


In [31]:
# Generate different dimensions of array
# Here we are creating 3 * 3 = 9 elements matrix with 0, 1, 2 rows and 0, 1, 2 columns

np.fromfunction(lambda i, j : i == j, (3, 3))     # fromfunction is a function that helps us in terms of arrays at any point of time

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i, j : i * j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [33]:
# Create a new 1-dimensional array from an iterable object using .fromiter() function

iterable = (i * i for i in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [34]:
# Create a new 1-D array initialized from text data in a string using .fromstring() function

np.fromstring('233 545 777', sep = ' ')   # separate the elements for array on the basis of sep i.e. equals to space ' ' in this case

array([233., 545., 777.])

In [35]:
np.fromstring('854,84777,8745', sep = ',')    # separate the elements for array on the basis of sep i.e. equals to comma ',' in this case

array([  854., 84777.,  8745.])

In [36]:
# Copy of an array vs an array pointing to a different location with the help of a new variable

a = np.array(l)
a

# Create a new variable and assign it a
c = a
c

# Now update 0th element of c

c[0] = 377

# This change will be reflected in c and a as both are pointing to the same location in the memory

a, c    # This is called a shallow copy

(array([377,   2,   3,   4]), array([377,   2,   3,   4]))

In [37]:
# Now contrary to shallow copy is an actual copy of an array using np.copy()

d = np.copy(a)
d             # This is not pointing to the same location as of 'a' in memory instead a copy of a is made in different location in memory and saved in variable 'd'

a[1] = 878

a, c, d       # The output shows that the above change was made in 'a' and 'c' but not made in 'd'

(array([377, 878,   3,   4]),
 array([377, 878,   3,   4]),
 array([377,   2,   3,   4]))

In [38]:
# Check the dimensions of an array

print('arr = ', arr)
print('Dimension of arr = ', arr.ndim)

array = np.array([[1, 2, 99], [3, 4, 4]])
print('array = ', array)
print('Dimension of array = ', array.ndim)

# Check the size of an array i.e. total no. of elements in an array

print('Size of array = ', array.size)

# Check the shape of an array i.e. no. of rows and colums in an array

print('Total no. rows and colums (size of an array) in array = ', array.shape)      # First number = no. of rows and second number = no. of columns

# Check the type of an array

print('Data type of array = ', array.dtype)

arr =  [1 2 3 4]
Dimension of arr =  1
array =  [[ 1  2 99]
 [ 3  4  4]]
Dimension of array =  2
Size of array =  6
Total no. rows and colums (size of an array) in array =  (2, 3)
Data type of array =  int64


In [39]:
# If one element in an array is float then NumPy converts all the elements of an array into float

array2 = np.array([(3, 3.3, 99, 687, 23), (8, 1, 5, 34, 36)])
array2, array2.dtype

(array([[  3. ,   3.3,  99. , 687. ,  23. ],
        [  8. ,   1. ,   5. ,  34. ,  36. ]]),
 dtype('float64'))

In [45]:
# Range in NumPy

a = np.arange(1, 10)        # arange() function works in the same manner as range() function in python does
print(a)                           # a is a 1-D array
print(type(a))

# Convert 'a' (1-D array/ vector) into a 2-D array (matrix) using .reshape(rows, cols)

a = np.arange(1, 10).reshape(3, 3)      # 1st number in reshape tells the number of rows and 2nd number tell the number of cols
print('After converting a into a matrix / 2-D array: ', a)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
After converting a into a matrix / 2-D array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
# Convert 'a' (10D array/ vector) into a 3-D array (tensor) using .reshape()

a = np.arange(1, 46).reshape(5, 3, 3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]]])