<a href="https://colab.research.google.com/github/Samiya-AW/NumPy-Numerical-Python-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
l = [1, 2, 3, 4]

In [6]:
# Convert list into an array

arr = np.array(l)
arr

type(arr)

numpy.ndarray

In [7]:
# Convert list into an array using np.asarray() and np.asanyarray() functions
l1 = [1, 2, 3, 4, 5]
arr1 = np.asarray(l1)
print(arr1)

l2 = [4, 5, 6, 100]
arr2 = np.asanyarray(l2)
arr2

[1 2 3 4 5]


array([  4,   5,   6, 100])

In [8]:
# Convert a list into a 2d array / matrix using np.matrix() function

mat = np.matrix(l2)
mat

# matrix is by default a 2d array
# matrix is a subset of an array

matrix([[  4,   5,   6, 100]])

In [9]:
# dimensions of array
# 2D array

array = np.array([[1, 2], [3, 4]])
print(array)
array

[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

In [10]:
# Print the total number of rows and columns in an array

array.shape

(2, 2)

In [11]:
# Size of an array / total number of elements in an array

array.size

4

In [12]:
# Dimension of an array

array.ndim

2

In [13]:
# 3D array

arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
    ])

print(arr_3d)
print("\nDimensions of arr_3d = ", arr_3d.ndim)
print("Shape (no. of rows and columns) of arr_3d = ", arr_3d.shape)
print("Total number of elements in arr_3d = ", arr_3d.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimensions of arr_3d =  3
Shape (no. of rows and columns) of arr_3d =  (2, 2, 3)
Total number of elements in arr_3d =  12


In [14]:
# Generate different dimensions of array
# Here we are creating 3 * 3 = 9 elements matrix with 0, 1, 2 rows and 0, 1, 2 columns

np.fromfunction(lambda i, j : i == j, (3, 3)) # fromfunction is a function that helps us in terms of arrays at any point of time

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [16]:
np.fromfunction(lambda i, j : i * j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [18]:
# Create a new 1-dimensional array from an iterable object

iterable = (i * i for i in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])